### ISSUE TITLE
Expecting optional fields (TypeError: Cannot Read properties uri)

### ISSUE THREAD

**Issue by ReversingWithMe** [trailofbits/vscode-sarif-explorer#12]
capa\example.sarif": Error: Parsing failed: TypeError: Cannot read properties of undefined (reading 'uri').

I believe the source of this is targeting source-based sarif files, and maybe this may need a few tweaks for looking at other types of sarif files (which may not make sense for your use-case).

Example sarif file, stripped directory absolute path
[example.zip](https://github.com/trailofbits/vscode-sarif-explorer/files/14734896/example.zip)

**Comment by Vasco-jofra** [comment]
Thank you for the report and for the SARIF reproducer, I'll look into it

**Comment by Vasco-jofra** [comment]
@ReversingWithMe I fixed this bug. You won't be able to jump to the corresponding address in the binary, of course, since VSCode is not a tool to visualize binaries, but you should be able to browse the results and see the problematic addresses that correspond to them. Let me know if you have any other issues or feature requests!
